inputs:
  raw_path: "data/raw/sample_report.csv"

outputs:
  clean_dir: "data/clean/"

format:
  delimiter: ";"
  decimal: ","
  thousands: "."
  date_format: "%d/%m/%Y"

schema:
  required_columns:
    - date
    - amount
    - vat
    - total
    - delivery_note
    - customer_id
    - invoice_num

storage:
  use_s3: false
  s3_bucket: "juanbravo-annual-delivery-notes"
  s3_prefix_raw: "raw_data/"
  s3_prefix_clean: "clean_data/"